import { Hono } from "hono";
import { createFactory } from "hono/factory";
import type { BrokerMonthlyReport } from "../../../contracts";
import { createDb } from "../../../db";
import type { ApiEnv } from "../../../env";
import { renderTextPdf } from "../../../lib/pdf";
import { loadReports } from "./reports.repository";

const factory = createFactory<ApiEnv>();

export const reportRoutes = new Hono<ApiEnv>();

function reportLines(report: BrokerMonthlyReport): string {
	const money = (value: number) => `IDR ${value.toLocaleString("en-US")}`;
	const lines = [
		{
			text: "GreenShift - Monthly Project Monitoring Report",
			size: 16,
			bold: true,
		},
		{
			text: "Read-only monitoring report provided to the assigned broker.",
			gap: 6,
		},
		{ text: "" },
		{ text: report.projectTitle, size: 13, bold: true, gap: 8 },
		{ text: `Company: ${report.companyName}` },
		{ text: `Vendor: ${report.vendorName ?? "Not recorded"}` },
		{ text: `Reporting period: ${report.period}` },
		{ text: `Overall status: ${report.overallStatus.replace(/_/g, " ")}` },
		{ text: `Published: ${report.submittedAt.slice(0, 10)}` },
		{ text: "" },
		{ text: "Project Progress", bold: true, gap: 8 },
		{ text: `Planned progress: ${report.plannedProgressPercent}%` },
		{ text: `Actual progress: ${report.actualProgressPercent}%` },
		{ text: `Completed milestones: ${report.completedMilestonesCount}` },
		{
			text: `Current milestone: ${report.currentMilestoneTitle ?? "All milestones completed"}`,
		},
		{ text: "" },
		{ text: "Financial Performance", bold: true, gap: 8 },
		{ text: `Planned budget: ${money(report.plannedBudgetAmount)}` },
		{ text: `Actual spending: ${money(report.actualSpendingAmount)}` },
		{
			text: `Budget variance: ${money(report.actualSpendingAmount - report.plannedBudgetAmount)}`,
		},
		{ text: `Projected ROI: ${report.projectedRoiPercent}% per year` },
		{
			text: `Measured ROI performance: ${report.actualRoiPerformancePercent}%`,
		},
		{ text: "" },
		{ text: "Energy Performance", bold: true, gap: 8 },
		{
			text: `Expected savings: ${report.expectedEnergySavingsKwh.toLocaleString("en-US")} kWh`,
		},
		{
			text: `Actual savings: ${report.actualEnergySavingsKwh.toLocaleString("en-US")} kWh`,
		},
		{ text: "" },
		{ text: "Environmental Performance", bold: true, gap: 8 },
		{
			text: `Expected emission reduction: ${report.expectedCarbonReductionTons} tCO2e`,
		},
		{
			text: `Measured emission reduction: ${report.actualCarbonReductionTons} tCO2e`,
		},
		{ text: "" },
		{ text: "Risks and Issues", bold: true, gap: 8 },
		...(report.detectedRisksOrAnomalies.length
			? report.detectedRisksOrAnomalies.map((risk) => ({ text: `- ${risk}` }))
			: [{ text: "- No risks or anomalies recorded for this period." }]),
		{ text: "" },
		{ text: "Overall Conclusion", bold: true, gap: 8 },
		{ text: report.overallConclusion },
		{ text: "" },
		{
			text: "This report is generated by GreenShift and cannot be modified by the broker.",
			gap: 10,
		},
	];
	return renderTextPdf(lines);
}

// ── monthly reports (§30-§34) ─────────────────────────────
reportRoutes.get(
	"/reports",
	...factory.createHandlers(async (c) => {
		const db = createDb(c.env.DB);
		const reports = await loadReports(db, c.get("user").id);
		return c.json({ reports });
	}),
);

reportRoutes.get(
	"/reports/:id",
	...factory.createHandlers(async (c) => {
		const id = Number(c.req.param("id"));
		if (!Number.isInteger(id) || id <= 0) {
			return c.json(
				{ error: { code: "VALIDATION", message: "Invalid ID" } },
				400,
			);
		}
		const db = createDb(c.env.DB);
		const [report] = await loadReports(db, c.get("user").id, id);
		if (!report) {
			return c.json(
				{ error: { code: "NOT_FOUND", message: "Report not found" } },
				404,
			);
		}
		return c.json({ report });
	}),
);

reportRoutes.get(
	"/reports/:id/pdf",
	...factory.createHandlers(async (c) => {
		const id = Number(c.req.param("id"));
		if (!Number.isInteger(id) || id <= 0) {
			return c.json(
				{ error: { code: "VALIDATION", message: "Invalid ID" } },
				400,
			);
		}
		const db = createDb(c.env.DB);
		const [report] = await loadReports(db, c.get("user").id, id);
		if (!report) {
			return c.json(
				{ error: { code: "NOT_FOUND", message: "Report not found" } },
				404,
			);
		}

		const pdf = reportLines(report);
		const fileName = `GreenShift_Monitoring_${report.period}_${report.id}.pdf`;
		return new Response(pdf, {
			headers: {
				"content-type": "application/pdf",
				"content-disposition": `attachment; filename="${fileName}"`,
				"cache-control": "private, no-store",
			},
		});
	}),
);
