import type {
	BrokerAssignedProject,
	BrokerDocumentRequest,
	BrokerNotification,
	BrokerVerificationDetails,
	BrokerWorkloadMetrics,
	MonthlyProjectReport,
} from "./types";

export const initialBrokerVerification: BrokerVerificationDetails = {
	status: "VERIFIED",
	legalEntityName: "Capital Green Indonesia Securities Inc.",
	nib: "9120803410291",
	financialLicenseNumber: "KEP-45/D.04/2023",
	licenseAuthority: "Financial Services Authority (OJK)",
	legalDocUrl: "Deed_of_Establishment_Capital_Green.pdf",
	licenseDocUrl: "Securities_Underwriter_License_OJK.pdf",
	submittedAt: "2026-01-10T08:30:00Z",
	verifiedAt: "2026-01-10T08:35:00Z",
};

export const sampleAssignedProjects: BrokerAssignedProject[] = [
	{
		id: "brk-proj-1",
		title: "1.2 MWp Textile Factory Rooftop Solar PV Installation",
		companyName: "PT Sinar Tekstil Indonesia",
		companyEmail: "corporate@sinartekstil.co.id",
		vendorName: "PT Nusantara Energy Solution",
		industrySector: "Manufacturing & Textiles",
		location: "Cikarang, West Java",
		projectValue: 12100000000,
		lvvGrkStatus: "VERIFIED",
		lvvGrkVerificationDate: "2026-08-25",
		workflowStatus: "UNDER_REVIEW",
		isAccepted: true,
		assignedAt: "2026-08-28T10:00:00Z",
		outstandingRequestsCount: 1,
		lastReportDate: "2026-09-01",
		description:
			"1.2 MWp Rooftop Solar PV installation project with an estimated carbon emission reduction of 1,420 tCO₂e/year. Successfully validated under GHG LVV environmental standards.",
		riskAssessment: {
			overallRiskLevel: "Medium",
			financialRisk: "Low",
			technicalRisk: "Medium",
			implementationRisk: "Medium",
			environmentalRisk: "Low",
			notes:
				"Operational and environmental risks are very low. GHG LVV has verified the emission baseline calculation methodology.",
		},
		bondInfo: {
			status: "IN_PROGRESS",
			totalAmount: 12000000000,
			tenorMonths: 36,
			couponRatePercent: 8.75,
			issuanceDate: "2026-10-01",
			maturityDate: "2029-10-01",
			brokerRepresentative: "Budi Santoso, CFA",
		},
		financialProjections: {
			irrPercent: 18.2,
			npvAmount: 3450000000,
			paybackYears: 4.2,
		},
	},
	{
		id: "brk-proj-2",
		title: "High-Efficiency HVAC & Smart Chiller Retrofit",
		companyName: "PT Sentra Graha Medika",
		companyEmail: "finance@sentragraha.co.id",
		vendorName: "PT Eco Power Indonesia",
		industrySector: "Healthcare & Hospitals",
		location: "Surabaya, East Java",
		projectValue: 8350000000,
		lvvGrkStatus: "VERIFIED",
		lvvGrkVerificationDate: "2026-08-20",
		workflowStatus: "READY_FOR_BOND_ISSUANCE",
		isAccepted: true,
		assignedAt: "2026-08-22T14:30:00Z",
		outstandingRequestsCount: 0,
		lastReportDate: "2026-09-01",
		description:
			"Central chiller retrofit for hospital sterile zones with estimated power savings of 28%. All financial and technical document reviews have been approved by the Broker.",
		riskAssessment: {
			overallRiskLevel: "Low",
			financialRisk: "Low",
			technicalRisk: "Low",
			implementationRisk: "Medium",
			environmentalRisk: "Low",
			notes:
				"Hospital cash flow predictability is exceptionally stable. Credit risk is classified as very low.",
		},
		bondInfo: {
			status: "IN_PROGRESS",
			totalAmount: 8000000000,
			tenorMonths: 24,
			couponRatePercent: 8.25,
			issuanceDate: "2026-09-25",
			maturityDate: "2028-09-25",
			brokerRepresentative: "Dewi Lestari, SE",
		},
		financialProjections: {
			irrPercent: 21.5,
			npvAmount: 2800000000,
			paybackYears: 3.5,
		},
	},
	{
		id: "brk-proj-3",
		title: "10 Tons/Hour Smart Biomass Boiler Conversion",
		companyName: "PT Agro Industri Nusantara",
		companyEmail: "info@agronusantara.co.id",
		vendorName: "PT Bio Thermal Energy",
		industrySector: "Agriculture & Food",
		location: "Lampung, Indonesia",
		projectValue: 11500000000,
		lvvGrkStatus: "VERIFIED",
		lvvGrkVerificationDate: "2026-09-02",
		workflowStatus: "ASSIGNED",
		isAccepted: false,
		assignedAt: "2026-09-04T09:00:00Z",
		outstandingRequestsCount: 2,
		description:
			"Substitution of coal with palm kernel shells in agricultural crop drying systems. Newly allocated by the Client Company to the Broker and requires initial acceptance.",
		riskAssessment: {
			overallRiskLevel: "Medium",
			financialRisk: "Medium",
			technicalRisk: "Low",
			implementationRisk: "Medium",
			environmentalRisk: "Low",
			notes:
				"Local palm kernel shell feedstock supply requires long-term contract certainty review.",
		},
		bondInfo: {
			status: "NOT_STARTED",
			totalAmount: 11000000000,
			tenorMonths: 48,
			couponRatePercent: 9.0,
			brokerRepresentative: "Budi Santoso, CFA",
		},
		financialProjections: {
			irrPercent: 19.8,
			npvAmount: 3100000000,
			paybackYears: 4.0,
		},
	},
];

export const sampleDocumentRequests: BrokerDocumentRequest[] = [
	{
		id: "doc-req-1",
		projectId: "brk-proj-1",
		projectTitle: "1.2 MWp Textile Factory Rooftop Solar PV Installation",
		companyName: "PT Sinar Tekstil Indonesia",
		category: "Financial",
		documentTypeName: "Audited Financial Statements",
		requiredPeriod: "2025 (Full Year)",
		reason:
			"Required for solvency ratio analysis and green bond underwriting preparation.",
		deadlineDate: "2026-09-15",
		additionalNotes:
			"Please include an independent certified public accountant (CPA) opinion.",
		status: "SUBMITTED",
		submittedFileName: "Audited_Financial_Statements_SinarTekstil_2025.pdf",
		submittedFileUrl: "#",
		submittedAt: "2026-09-03T11:00:00Z",
	},
	{
		id: "doc-req-2",
		projectId: "brk-proj-1",
		projectTitle: "1.2 MWp Textile Factory Rooftop Solar PV Installation",
		companyName: "PT Sinar Tekstil Indonesia",
		category: "Legal",
		documentTypeName: "Roof & Factory Structure Building Permit",
		requiredPeriod: "2026-2051",
		reason:
			"Verification of factory building rights and roof structural load capacity for solar module installation.",
		deadlineDate: "2026-09-18",
		status: "REQUESTED",
	},
	{
		id: "doc-req-3",
		projectId: "brk-proj-2",
		projectTitle: "High-Efficiency HVAC & Smart Chiller Retrofit",
		companyName: "PT Sentra Graha Medika",
		category: "Technical",
		documentTypeName: "Daikin Magnetic Bearing Compressor Certification",
		requiredPeriod: "5-Year Warranty",
		reason:
			"Verification of primary equipment manufacturer warranty supporting operational cash flows.",
		deadlineDate: "2026-08-30",
		status: "APPROVED",
		submittedFileName: "Daikin_HVAC_Warranty_Certificate.pdf",
		submittedFileUrl: "#",
		submittedAt: "2026-08-28T16:20:00Z",
		reviewedAt: "2026-08-29T10:00:00Z",
	},
];

export const sampleMonthlyReports: MonthlyProjectReport[] = [
	{
		id: "rep-2026-08",
		projectId: "brk-proj-1",
		projectTitle: "1.2 MWp Textile Factory Rooftop Solar PV Installation",
		companyName: "PT Sinar Tekstil Indonesia",
		vendorName: "PT Nusantara Energy Solution",
		period: "2026-08",
		overallStatus: "ON_TRACK",
		plannedProgressPercent: 65,
		actualProgressPercent: 68,
		completedMilestonesCount: 2,
		currentMilestoneTitle: "Racking Installation & DC Wiring Works",
		plannedBudgetAmount: 8900000000,
		actualSpendingAmount: 8750000000,
		expectedEnergySavingsKwh: 42500,
		actualEnergySavingsKwh: 44200,
		expectedCarbonReductionTons: 36.1,
		actualCarbonReductionTons: 37.5,
		projectedRoiPercent: 18.2,
		actualRoiPerformancePercent: 18.8,
		detectedRisksOrAnomalies: [
			"Phase II inverter delivery arrived 3 days ahead of schedule.",
		],
		overallConclusion:
			"Project execution is ON TRACK, exceeding physical progress targets by 3%. Energy savings reached 104% of baseline.",
		submittedAt: "2026-09-01T09:00:00Z",
		pdfExportUrl: "Report_August_2026_SolarPV.pdf",
	},
	{
		id: "rep-2026-07",
		projectId: "brk-proj-1",
		projectTitle: "1.2 MWp Textile Factory Rooftop Solar PV Installation",
		companyName: "PT Sinar Tekstil Indonesia",
		vendorName: "PT Nusantara Energy Solution",
		period: "2026-07",
		overallStatus: "ON_TRACK",
		plannedProgressPercent: 40,
		actualProgressPercent: 42,
		completedMilestonesCount: 1,
		currentMilestoneTitle: "Procurement of Solar Panels & Main Inverters",
		plannedBudgetAmount: 5200000000,
		actualSpendingAmount: 5150000000,
		expectedEnergySavingsKwh: 40000,
		actualEnergySavingsKwh: 41200,
		expectedCarbonReductionTons: 34.0,
		actualCarbonReductionTons: 35.1,
		projectedRoiPercent: 18.2,
		actualRoiPerformancePercent: 18.5,
		detectedRisksOrAnomalies: [],
		overallConclusion:
			"Primary equipment and material procurement completed 100% without port logistics bottlenecks.",
		submittedAt: "2026-08-01T10:00:00Z",
		pdfExportUrl: "Report_July_2026_SolarPV.pdf",
	},
];

export const sampleBrokerNotifications: BrokerNotification[] = [
	{
		id: "notif-brk-1",
		category: "Documents",
		title: "New Financial Document Uploaded by Client",
		message:
			"PT Sinar Tekstil Indonesia uploaded 2025 Audited Financial Statements for Broker review.",
		timestamp: "15 minutes ago",
		isRead: false,
		linkUrl: "/broker/document-requests",
	},
	{
		id: "notif-brk-2",
		category: "Assignment",
		title: "New Green Project Assignment Confirmed",
		message:
			"PT Agro Industri Nusantara assigned the Biomass Boiler Conversion project (GHG LVV Verified) to you.",
		timestamp: "2 hours ago",
		isRead: false,
		linkUrl: "/broker/projects",
	},
	{
		id: "notif-brk-3",
		category: "Reporting",
		title: "August 2026 Monthly Report Available",
		message:
			"Monthly monitoring report for the Textile Factory Solar PV project has been published (Status: ON TRACK).",
		timestamp: "1 day ago",
		isRead: true,
		linkUrl: "/broker/monthly-reports",
	},
];

export const sampleWorkloadMetrics: BrokerWorkloadMetrics = {
	assignedProjectsCount: 3,
	awaitingReviewCount: 1,
	outstandingRequestsCount: 2,
	inBondProcessingCount: 2,
	underMonitoringCount: 1,
};
