/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObligasiRouteImport } from './routes/obligasi'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthBusinessRouteImport } from './routes/_auth.business'
import { Route as AuthProfileRouteImport } from './routes/_auth.profile'
import { Route as AuthVendorRouteImport } from './routes/_auth.vendor'
import { Route as ObligasiIndexRouteImport } from './routes/obligasi.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'
import { Route as AuthAdminAnalyticsRouteImport } from './routes/_auth.admin.analytics'
import { Route as AuthAdminAuditLogsRouteImport } from './routes/_auth.admin.audit-logs'
import { Route as AuthAdminProjectsRouteImport } from './routes/_auth.admin.projects'
import { Route as AuthAdminSystemRouteImport } from './routes/_auth.admin.system'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth.admin.users'
import { Route as AuthAdminVendorsRouteImport } from './routes/_auth.admin.vendors'
import { Route as AuthBusinessIndexRouteImport } from './routes/_auth.business.index'
import { Route as AuthVendorIndexRouteImport } from './routes/_auth.vendor.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObligasiRoute = ObligasiRouteImport.update({
  id: '/obligasi',
  path: '/obligasi',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBusinessRoute = AuthBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorRoute = AuthVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthRoute,
} as any)
const ObligasiIndexRoute = ObligasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObligasiRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAnalyticsRoute = AuthAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAuditLogsRoute = AuthAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminProjectsRoute = AuthAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminSystemRoute = AuthAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminVendorsRoute = AuthAdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthBusinessIndexRoute = AuthBusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBusinessRoute,
} as any)
const AuthVendorIndexRoute = AuthVendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthVendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/obligasi': typeof ObligasiRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/business': typeof AuthBusinessRouteWithChildren
  '/profile': typeof AuthProfileRoute
  '/vendor': typeof AuthVendorRouteWithChildren
  '/obligasi/': typeof ObligasiIndexRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/projects': typeof AuthAdminProjectsRoute
  '/admin/system': typeof AuthAdminSystemRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin/vendors': typeof AuthAdminVendorsRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/business/': typeof AuthBusinessIndexRoute
  '/vendor/': typeof AuthVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthProfileRoute
  '/obligasi': typeof ObligasiIndexRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/projects': typeof AuthAdminProjectsRoute
  '/admin/system': typeof AuthAdminSystemRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin/vendors': typeof AuthAdminVendorsRoute
  '/admin': typeof AuthAdminIndexRoute
  '/business': typeof AuthBusinessIndexRoute
  '/vendor': typeof AuthVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/obligasi': typeof ObligasiRouteWithChildren
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/business': typeof AuthBusinessRouteWithChildren
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/vendor': typeof AuthVendorRouteWithChildren
  '/obligasi/': typeof ObligasiIndexRoute
  '/_auth/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/_auth/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/_auth/admin/projects': typeof AuthAdminProjectsRoute
  '/_auth/admin/system': typeof AuthAdminSystemRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/admin/vendors': typeof AuthAdminVendorsRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/business/': typeof AuthBusinessIndexRoute
  '/_auth/vendor/': typeof AuthVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/obligasi'
    | '/register'
    | '/admin'
    | '/business'
    | '/profile'
    | '/vendor'
    | '/obligasi/'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/projects'
    | '/admin/system'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin/'
    | '/business/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/obligasi'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/projects'
    | '/admin/system'
    | '/admin/users'
    | '/admin/vendors'
    | '/admin'
    | '/business'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/obligasi'
    | '/register'
    | '/_auth/admin'
    | '/_auth/business'
    | '/_auth/profile'
    | '/_auth/vendor'
    | '/obligasi/'
    | '/_auth/admin/analytics'
    | '/_auth/admin/audit-logs'
    | '/_auth/admin/projects'
    | '/_auth/admin/system'
    | '/_auth/admin/users'
    | '/_auth/admin/vendors'
    | '/_auth/admin/'
    | '/_auth/business/'
    | '/_auth/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ObligasiRoute: typeof ObligasiRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obligasi': {
      id: '/obligasi'
      path: '/obligasi'
      fullPath: '/obligasi'
      preLoaderRoute: typeof ObligasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/business': {
      id: '/_auth/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthBusinessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor': {
      id: '/_auth/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthVendorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/obligasi/': {
      id: '/obligasi/'
      path: '/'
      fullPath: '/obligasi/'
      preLoaderRoute: typeof ObligasiIndexRouteImport
      parentRoute: typeof ObligasiRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/analytics': {
      id: '/_auth/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthAdminAnalyticsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/audit-logs': {
      id: '/_auth/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthAdminAuditLogsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/projects': {
      id: '/_auth/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthAdminProjectsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/system': {
      id: '/_auth/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthAdminSystemRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/vendors': {
      id: '/_auth/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthAdminVendorsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/business/': {
      id: '/_auth/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthBusinessIndexRouteImport
      parentRoute: typeof AuthBusinessRoute
    }
    '/_auth/vendor/': {
      id: '/_auth/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthVendorIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminAnalyticsRoute: typeof AuthAdminAnalyticsRoute
  AuthAdminAuditLogsRoute: typeof AuthAdminAuditLogsRoute
  AuthAdminProjectsRoute: typeof AuthAdminProjectsRoute
  AuthAdminSystemRoute: typeof AuthAdminSystemRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminVendorsRoute: typeof AuthAdminVendorsRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAnalyticsRoute: AuthAdminAnalyticsRoute,
  AuthAdminAuditLogsRoute: AuthAdminAuditLogsRoute,
  AuthAdminProjectsRoute: AuthAdminProjectsRoute,
  AuthAdminSystemRoute: AuthAdminSystemRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminVendorsRoute: AuthAdminVendorsRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthBusinessRouteChildren {
  AuthBusinessIndexRoute: typeof AuthBusinessIndexRoute
}

const AuthBusinessRouteChildren: AuthBusinessRouteChildren = {
  AuthBusinessIndexRoute: AuthBusinessIndexRoute,
}

const AuthBusinessRouteWithChildren = AuthBusinessRoute._addFileChildren(
  AuthBusinessRouteChildren,
)

interface AuthVendorRouteChildren {
  AuthVendorIndexRoute: typeof AuthVendorIndexRoute
}

const AuthVendorRouteChildren: AuthVendorRouteChildren = {
  AuthVendorIndexRoute: AuthVendorIndexRoute,
}

const AuthVendorRouteWithChildren = AuthVendorRoute._addFileChildren(
  AuthVendorRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthBusinessRoute: typeof AuthBusinessRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthVendorRoute: typeof AuthVendorRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthBusinessRoute: AuthBusinessRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthVendorRoute: AuthVendorRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ObligasiRouteChildren {
  ObligasiIndexRoute: typeof ObligasiIndexRoute
}

const ObligasiRouteChildren: ObligasiRouteChildren = {
  ObligasiIndexRoute: ObligasiIndexRoute,
}

const ObligasiRouteWithChildren = ObligasiRoute._addFileChildren(
  ObligasiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ObligasiRoute: ObligasiRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
