/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as BondsRouteImport } from './routes/bonds'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as AuthBrokerRouteImport } from './routes/_auth.broker'
import { Route as AuthBusinessRouteImport } from './routes/_auth.business'
import { Route as AuthVendorRouteImport } from './routes/_auth.vendor'
import { Route as BondsIndexRouteImport } from './routes/bonds.index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth.admin.index'
import { Route as AuthAdminAnalyticsRouteImport } from './routes/_auth.admin.analytics'
import { Route as AuthAdminAuditLogsRouteImport } from './routes/_auth.admin.audit-logs'
import { Route as AuthAdminProjectsRouteImport } from './routes/_auth.admin.projects'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth.admin.users'
import { Route as AuthAdminVendorsRouteImport } from './routes/_auth.admin.vendors'
import { Route as AuthBrokerIndexRouteImport } from './routes/_auth.broker.index'
import { Route as AuthBrokerDocumentRequestsRouteImport } from './routes/_auth.broker.document-requests'
import { Route as AuthBrokerSettingsRouteImport } from './routes/_auth.broker.settings'
import { Route as AuthBusinessIndexRouteImport } from './routes/_auth.business.index'
import { Route as AuthBusinessProyekRouteImport } from './routes/_auth.business.proyek'
import { Route as AuthVendorIndexRouteImport } from './routes/_auth.vendor.index'
import { Route as AuthVendorDealsRouteImport } from './routes/_auth.vendor.deals'
import { Route as AuthVendorNotificationsRouteImport } from './routes/_auth.vendor.notifications'
import { Route as AuthVendorOpportunitiesRouteImport } from './routes/_auth.vendor.opportunities'
import { Route as AuthVendorPerformanceRouteImport } from './routes/_auth.vendor.performance'
import { Route as AuthVendorPortfolioPerformanceRouteImport } from './routes/_auth.vendor.portfolio-performance'
import { Route as AuthVendorSettingsRouteImport } from './routes/_auth.vendor.settings'
import { Route as AuthBrokerMonthlyReportsIndexRouteImport } from './routes/_auth.broker.monthly-reports.index'
import { Route as AuthBrokerMonthlyReportsIdRouteImport } from './routes/_auth.broker.monthly-reports.$id'
import { Route as AuthBrokerProjectsIndexRouteImport } from './routes/_auth.broker.projects.index'
import { Route as AuthBrokerProjectsIdRouteImport } from './routes/_auth.broker.projects.$id'
import { Route as AuthVendorActiveProjectsIndexRouteImport } from './routes/_auth.vendor.active-projects.index'
import { Route as AuthVendorActiveProjectsIdRouteImport } from './routes/_auth.vendor.active-projects.$id'
import { Route as AuthVendorPortfolioIndexRouteImport } from './routes/_auth.vendor.portfolio.index'
import { Route as AuthVendorPortfolioIdRouteImport } from './routes/_auth.vendor.portfolio.$id'
import { Route as AuthVendorProjectsIndexRouteImport } from './routes/_auth.vendor.projects.index'
import { Route as AuthVendorProjectsIdRouteImport } from './routes/_auth.vendor.projects.$id'
import { Route as AuthVendorTendersIndexRouteImport } from './routes/_auth.vendor.tenders.index'
import { Route as AuthVendorTendersIdRouteImport } from './routes/_auth.vendor.tenders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BondsRoute = BondsRouteImport.update({
  id: '/bonds',
  path: '/bonds',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBrokerRoute = AuthBrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBusinessRoute = AuthBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVendorRoute = AuthVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthRoute,
} as any)
const BondsIndexRoute = BondsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BondsRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAnalyticsRoute = AuthAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminAuditLogsRoute = AuthAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminProjectsRoute = AuthAdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthAdminVendorsRoute = AuthAdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthBrokerIndexRoute = AuthBrokerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBrokerRoute,
} as any)
const AuthBrokerDocumentRequestsRoute =
  AuthBrokerDocumentRequestsRouteImport.update({
    id: '/document-requests',
    path: '/document-requests',
    getParentRoute: () => AuthBrokerRoute,
  } as any)
const AuthBrokerSettingsRoute = AuthBrokerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthBrokerRoute,
} as any)
const AuthBusinessIndexRoute = AuthBusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBusinessRoute,
} as any)
const AuthBusinessProyekRoute = AuthBusinessProyekRouteImport.update({
  id: '/proyek',
  path: '/proyek',
  getParentRoute: () => AuthBusinessRoute,
} as any)
const AuthVendorIndexRoute = AuthVendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorDealsRoute = AuthVendorDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorNotificationsRoute = AuthVendorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorOpportunitiesRoute = AuthVendorOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorPerformanceRoute = AuthVendorPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorPortfolioPerformanceRoute =
  AuthVendorPortfolioPerformanceRouteImport.update({
    id: '/portfolio-performance',
    path: '/portfolio-performance',
    getParentRoute: () => AuthVendorRoute,
  } as any)
const AuthVendorSettingsRoute = AuthVendorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthBrokerMonthlyReportsIndexRoute =
  AuthBrokerMonthlyReportsIndexRouteImport.update({
    id: '/monthly-reports/',
    path: '/monthly-reports/',
    getParentRoute: () => AuthBrokerRoute,
  } as any)
const AuthBrokerMonthlyReportsIdRoute =
  AuthBrokerMonthlyReportsIdRouteImport.update({
    id: '/monthly-reports/$id',
    path: '/monthly-reports/$id',
    getParentRoute: () => AuthBrokerRoute,
  } as any)
const AuthBrokerProjectsIndexRoute = AuthBrokerProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthBrokerRoute,
} as any)
const AuthBrokerProjectsIdRoute = AuthBrokerProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthBrokerRoute,
} as any)
const AuthVendorActiveProjectsIndexRoute =
  AuthVendorActiveProjectsIndexRouteImport.update({
    id: '/active-projects/',
    path: '/active-projects/',
    getParentRoute: () => AuthVendorRoute,
  } as any)
const AuthVendorActiveProjectsIdRoute =
  AuthVendorActiveProjectsIdRouteImport.update({
    id: '/active-projects/$id',
    path: '/active-projects/$id',
    getParentRoute: () => AuthVendorRoute,
  } as any)
const AuthVendorPortfolioIndexRoute =
  AuthVendorPortfolioIndexRouteImport.update({
    id: '/portfolio/',
    path: '/portfolio/',
    getParentRoute: () => AuthVendorRoute,
  } as any)
const AuthVendorPortfolioIdRoute = AuthVendorPortfolioIdRouteImport.update({
  id: '/portfolio/$id',
  path: '/portfolio/$id',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorProjectsIndexRoute = AuthVendorProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorProjectsIdRoute = AuthVendorProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorTendersIndexRoute = AuthVendorTendersIndexRouteImport.update({
  id: '/tenders/',
  path: '/tenders/',
  getParentRoute: () => AuthVendorRoute,
} as any)
const AuthVendorTendersIdRoute = AuthVendorTendersIdRouteImport.update({
  id: '/tenders/$id',
  path: '/tenders/$id',
  getParentRoute: () => AuthVendorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonds': typeof BondsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/broker': typeof AuthBrokerRouteWithChildren
  '/business': typeof AuthBusinessRouteWithChildren
  '/vendor': typeof AuthVendorRouteWithChildren
  '/bonds/': typeof BondsIndexRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/projects': typeof AuthAdminProjectsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin/vendors': typeof AuthAdminVendorsRoute
  '/broker/document-requests': typeof AuthBrokerDocumentRequestsRoute
  '/broker/settings': typeof AuthBrokerSettingsRoute
  '/business/proyek': typeof AuthBusinessProyekRoute
  '/vendor/deals': typeof AuthVendorDealsRoute
  '/vendor/notifications': typeof AuthVendorNotificationsRoute
  '/vendor/opportunities': typeof AuthVendorOpportunitiesRoute
  '/vendor/performance': typeof AuthVendorPerformanceRoute
  '/vendor/portfolio-performance': typeof AuthVendorPortfolioPerformanceRoute
  '/vendor/settings': typeof AuthVendorSettingsRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/broker/': typeof AuthBrokerIndexRoute
  '/business/': typeof AuthBusinessIndexRoute
  '/vendor/': typeof AuthVendorIndexRoute
  '/broker/monthly-reports/$id': typeof AuthBrokerMonthlyReportsIdRoute
  '/broker/projects/$id': typeof AuthBrokerProjectsIdRoute
  '/vendor/active-projects/$id': typeof AuthVendorActiveProjectsIdRoute
  '/vendor/portfolio/$id': typeof AuthVendorPortfolioIdRoute
  '/vendor/projects/$id': typeof AuthVendorProjectsIdRoute
  '/vendor/tenders/$id': typeof AuthVendorTendersIdRoute
  '/broker/monthly-reports/': typeof AuthBrokerMonthlyReportsIndexRoute
  '/broker/projects/': typeof AuthBrokerProjectsIndexRoute
  '/vendor/active-projects/': typeof AuthVendorActiveProjectsIndexRoute
  '/vendor/portfolio/': typeof AuthVendorPortfolioIndexRoute
  '/vendor/projects/': typeof AuthVendorProjectsIndexRoute
  '/vendor/tenders/': typeof AuthVendorTendersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/bonds': typeof BondsIndexRoute
  '/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/admin/projects': typeof AuthAdminProjectsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/admin/vendors': typeof AuthAdminVendorsRoute
  '/broker/document-requests': typeof AuthBrokerDocumentRequestsRoute
  '/broker/settings': typeof AuthBrokerSettingsRoute
  '/business/proyek': typeof AuthBusinessProyekRoute
  '/vendor/deals': typeof AuthVendorDealsRoute
  '/vendor/notifications': typeof AuthVendorNotificationsRoute
  '/vendor/opportunities': typeof AuthVendorOpportunitiesRoute
  '/vendor/performance': typeof AuthVendorPerformanceRoute
  '/vendor/portfolio-performance': typeof AuthVendorPortfolioPerformanceRoute
  '/vendor/settings': typeof AuthVendorSettingsRoute
  '/admin': typeof AuthAdminIndexRoute
  '/broker': typeof AuthBrokerIndexRoute
  '/business': typeof AuthBusinessIndexRoute
  '/vendor': typeof AuthVendorIndexRoute
  '/broker/monthly-reports/$id': typeof AuthBrokerMonthlyReportsIdRoute
  '/broker/projects/$id': typeof AuthBrokerProjectsIdRoute
  '/vendor/active-projects/$id': typeof AuthVendorActiveProjectsIdRoute
  '/vendor/portfolio/$id': typeof AuthVendorPortfolioIdRoute
  '/vendor/projects/$id': typeof AuthVendorProjectsIdRoute
  '/vendor/tenders/$id': typeof AuthVendorTendersIdRoute
  '/broker/monthly-reports': typeof AuthBrokerMonthlyReportsIndexRoute
  '/broker/projects': typeof AuthBrokerProjectsIndexRoute
  '/vendor/active-projects': typeof AuthVendorActiveProjectsIndexRoute
  '/vendor/portfolio': typeof AuthVendorPortfolioIndexRoute
  '/vendor/projects': typeof AuthVendorProjectsIndexRoute
  '/vendor/tenders': typeof AuthVendorTendersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/bonds': typeof BondsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/broker': typeof AuthBrokerRouteWithChildren
  '/_auth/business': typeof AuthBusinessRouteWithChildren
  '/_auth/vendor': typeof AuthVendorRouteWithChildren
  '/bonds/': typeof BondsIndexRoute
  '/_auth/admin/analytics': typeof AuthAdminAnalyticsRoute
  '/_auth/admin/audit-logs': typeof AuthAdminAuditLogsRoute
  '/_auth/admin/projects': typeof AuthAdminProjectsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/admin/vendors': typeof AuthAdminVendorsRoute
  '/_auth/broker/document-requests': typeof AuthBrokerDocumentRequestsRoute
  '/_auth/broker/settings': typeof AuthBrokerSettingsRoute
  '/_auth/business/proyek': typeof AuthBusinessProyekRoute
  '/_auth/vendor/deals': typeof AuthVendorDealsRoute
  '/_auth/vendor/notifications': typeof AuthVendorNotificationsRoute
  '/_auth/vendor/opportunities': typeof AuthVendorOpportunitiesRoute
  '/_auth/vendor/performance': typeof AuthVendorPerformanceRoute
  '/_auth/vendor/portfolio-performance': typeof AuthVendorPortfolioPerformanceRoute
  '/_auth/vendor/settings': typeof AuthVendorSettingsRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/broker/': typeof AuthBrokerIndexRoute
  '/_auth/business/': typeof AuthBusinessIndexRoute
  '/_auth/vendor/': typeof AuthVendorIndexRoute
  '/_auth/broker/monthly-reports/$id': typeof AuthBrokerMonthlyReportsIdRoute
  '/_auth/broker/projects/$id': typeof AuthBrokerProjectsIdRoute
  '/_auth/vendor/active-projects/$id': typeof AuthVendorActiveProjectsIdRoute
  '/_auth/vendor/portfolio/$id': typeof AuthVendorPortfolioIdRoute
  '/_auth/vendor/projects/$id': typeof AuthVendorProjectsIdRoute
  '/_auth/vendor/tenders/$id': typeof AuthVendorTendersIdRoute
  '/_auth/broker/monthly-reports/': typeof AuthBrokerMonthlyReportsIndexRoute
  '/_auth/broker/projects/': typeof AuthBrokerProjectsIndexRoute
  '/_auth/vendor/active-projects/': typeof AuthVendorActiveProjectsIndexRoute
  '/_auth/vendor/portfolio/': typeof AuthVendorPortfolioIndexRoute
  '/_auth/vendor/projects/': typeof AuthVendorProjectsIndexRoute
  '/_auth/vendor/tenders/': typeof AuthVendorTendersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonds'
    | '/login'
    | '/register'
    | '/admin'
    | '/broker'
    | '/business'
    | '/vendor'
    | '/bonds/'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/vendors'
    | '/broker/document-requests'
    | '/broker/settings'
    | '/business/proyek'
    | '/vendor/deals'
    | '/vendor/notifications'
    | '/vendor/opportunities'
    | '/vendor/performance'
    | '/vendor/portfolio-performance'
    | '/vendor/settings'
    | '/admin/'
    | '/broker/'
    | '/business/'
    | '/vendor/'
    | '/broker/monthly-reports/$id'
    | '/broker/projects/$id'
    | '/vendor/active-projects/$id'
    | '/vendor/portfolio/$id'
    | '/vendor/projects/$id'
    | '/vendor/tenders/$id'
    | '/broker/monthly-reports/'
    | '/broker/projects/'
    | '/vendor/active-projects/'
    | '/vendor/portfolio/'
    | '/vendor/projects/'
    | '/vendor/tenders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/bonds'
    | '/admin/analytics'
    | '/admin/audit-logs'
    | '/admin/projects'
    | '/admin/users'
    | '/admin/vendors'
    | '/broker/document-requests'
    | '/broker/settings'
    | '/business/proyek'
    | '/vendor/deals'
    | '/vendor/notifications'
    | '/vendor/opportunities'
    | '/vendor/performance'
    | '/vendor/portfolio-performance'
    | '/vendor/settings'
    | '/admin'
    | '/broker'
    | '/business'
    | '/vendor'
    | '/broker/monthly-reports/$id'
    | '/broker/projects/$id'
    | '/vendor/active-projects/$id'
    | '/vendor/portfolio/$id'
    | '/vendor/projects/$id'
    | '/vendor/tenders/$id'
    | '/broker/monthly-reports'
    | '/broker/projects'
    | '/vendor/active-projects'
    | '/vendor/portfolio'
    | '/vendor/projects'
    | '/vendor/tenders'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/bonds'
    | '/login'
    | '/register'
    | '/_auth/admin'
    | '/_auth/broker'
    | '/_auth/business'
    | '/_auth/vendor'
    | '/bonds/'
    | '/_auth/admin/analytics'
    | '/_auth/admin/audit-logs'
    | '/_auth/admin/projects'
    | '/_auth/admin/users'
    | '/_auth/admin/vendors'
    | '/_auth/broker/document-requests'
    | '/_auth/broker/settings'
    | '/_auth/business/proyek'
    | '/_auth/vendor/deals'
    | '/_auth/vendor/notifications'
    | '/_auth/vendor/opportunities'
    | '/_auth/vendor/performance'
    | '/_auth/vendor/portfolio-performance'
    | '/_auth/vendor/settings'
    | '/_auth/admin/'
    | '/_auth/broker/'
    | '/_auth/business/'
    | '/_auth/vendor/'
    | '/_auth/broker/monthly-reports/$id'
    | '/_auth/broker/projects/$id'
    | '/_auth/vendor/active-projects/$id'
    | '/_auth/vendor/portfolio/$id'
    | '/_auth/vendor/projects/$id'
    | '/_auth/vendor/tenders/$id'
    | '/_auth/broker/monthly-reports/'
    | '/_auth/broker/projects/'
    | '/_auth/vendor/active-projects/'
    | '/_auth/vendor/portfolio/'
    | '/_auth/vendor/projects/'
    | '/_auth/vendor/tenders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  BondsRoute: typeof BondsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonds': {
      id: '/bonds'
      path: '/bonds'
      fullPath: '/bonds'
      preLoaderRoute: typeof BondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/broker': {
      id: '/_auth/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof AuthBrokerRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/business': {
      id: '/_auth/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthBusinessRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/vendor': {
      id: '/_auth/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthVendorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/bonds/': {
      id: '/bonds/'
      path: '/'
      fullPath: '/bonds/'
      preLoaderRoute: typeof BondsIndexRouteImport
      parentRoute: typeof BondsRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/analytics': {
      id: '/_auth/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthAdminAnalyticsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/audit-logs': {
      id: '/_auth/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthAdminAuditLogsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/projects': {
      id: '/_auth/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthAdminProjectsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/admin/vendors': {
      id: '/_auth/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthAdminVendorsRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/broker/': {
      id: '/_auth/broker/'
      path: '/'
      fullPath: '/broker/'
      preLoaderRoute: typeof AuthBrokerIndexRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/broker/document-requests': {
      id: '/_auth/broker/document-requests'
      path: '/document-requests'
      fullPath: '/broker/document-requests'
      preLoaderRoute: typeof AuthBrokerDocumentRequestsRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/broker/settings': {
      id: '/_auth/broker/settings'
      path: '/settings'
      fullPath: '/broker/settings'
      preLoaderRoute: typeof AuthBrokerSettingsRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/business/': {
      id: '/_auth/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthBusinessIndexRouteImport
      parentRoute: typeof AuthBusinessRoute
    }
    '/_auth/business/proyek': {
      id: '/_auth/business/proyek'
      path: '/proyek'
      fullPath: '/business/proyek'
      preLoaderRoute: typeof AuthBusinessProyekRouteImport
      parentRoute: typeof AuthBusinessRoute
    }
    '/_auth/vendor/': {
      id: '/_auth/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthVendorIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/deals': {
      id: '/_auth/vendor/deals'
      path: '/deals'
      fullPath: '/vendor/deals'
      preLoaderRoute: typeof AuthVendorDealsRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/notifications': {
      id: '/_auth/vendor/notifications'
      path: '/notifications'
      fullPath: '/vendor/notifications'
      preLoaderRoute: typeof AuthVendorNotificationsRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/opportunities': {
      id: '/_auth/vendor/opportunities'
      path: '/opportunities'
      fullPath: '/vendor/opportunities'
      preLoaderRoute: typeof AuthVendorOpportunitiesRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/performance': {
      id: '/_auth/vendor/performance'
      path: '/performance'
      fullPath: '/vendor/performance'
      preLoaderRoute: typeof AuthVendorPerformanceRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/portfolio-performance': {
      id: '/_auth/vendor/portfolio-performance'
      path: '/portfolio-performance'
      fullPath: '/vendor/portfolio-performance'
      preLoaderRoute: typeof AuthVendorPortfolioPerformanceRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/settings': {
      id: '/_auth/vendor/settings'
      path: '/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof AuthVendorSettingsRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/broker/monthly-reports/': {
      id: '/_auth/broker/monthly-reports/'
      path: '/monthly-reports'
      fullPath: '/broker/monthly-reports/'
      preLoaderRoute: typeof AuthBrokerMonthlyReportsIndexRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/broker/monthly-reports/$id': {
      id: '/_auth/broker/monthly-reports/$id'
      path: '/monthly-reports/$id'
      fullPath: '/broker/monthly-reports/$id'
      preLoaderRoute: typeof AuthBrokerMonthlyReportsIdRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/broker/projects/': {
      id: '/_auth/broker/projects/'
      path: '/projects'
      fullPath: '/broker/projects/'
      preLoaderRoute: typeof AuthBrokerProjectsIndexRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/broker/projects/$id': {
      id: '/_auth/broker/projects/$id'
      path: '/projects/$id'
      fullPath: '/broker/projects/$id'
      preLoaderRoute: typeof AuthBrokerProjectsIdRouteImport
      parentRoute: typeof AuthBrokerRoute
    }
    '/_auth/vendor/active-projects/': {
      id: '/_auth/vendor/active-projects/'
      path: '/active-projects'
      fullPath: '/vendor/active-projects/'
      preLoaderRoute: typeof AuthVendorActiveProjectsIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/active-projects/$id': {
      id: '/_auth/vendor/active-projects/$id'
      path: '/active-projects/$id'
      fullPath: '/vendor/active-projects/$id'
      preLoaderRoute: typeof AuthVendorActiveProjectsIdRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/portfolio/': {
      id: '/_auth/vendor/portfolio/'
      path: '/portfolio'
      fullPath: '/vendor/portfolio/'
      preLoaderRoute: typeof AuthVendorPortfolioIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/portfolio/$id': {
      id: '/_auth/vendor/portfolio/$id'
      path: '/portfolio/$id'
      fullPath: '/vendor/portfolio/$id'
      preLoaderRoute: typeof AuthVendorPortfolioIdRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/projects/': {
      id: '/_auth/vendor/projects/'
      path: '/projects'
      fullPath: '/vendor/projects/'
      preLoaderRoute: typeof AuthVendorProjectsIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/projects/$id': {
      id: '/_auth/vendor/projects/$id'
      path: '/projects/$id'
      fullPath: '/vendor/projects/$id'
      preLoaderRoute: typeof AuthVendorProjectsIdRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/tenders/': {
      id: '/_auth/vendor/tenders/'
      path: '/tenders'
      fullPath: '/vendor/tenders/'
      preLoaderRoute: typeof AuthVendorTendersIndexRouteImport
      parentRoute: typeof AuthVendorRoute
    }
    '/_auth/vendor/tenders/$id': {
      id: '/_auth/vendor/tenders/$id'
      path: '/tenders/$id'
      fullPath: '/vendor/tenders/$id'
      preLoaderRoute: typeof AuthVendorTendersIdRouteImport
      parentRoute: typeof AuthVendorRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminAnalyticsRoute: typeof AuthAdminAnalyticsRoute
  AuthAdminAuditLogsRoute: typeof AuthAdminAuditLogsRoute
  AuthAdminProjectsRoute: typeof AuthAdminProjectsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminVendorsRoute: typeof AuthAdminVendorsRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminAnalyticsRoute: AuthAdminAnalyticsRoute,
  AuthAdminAuditLogsRoute: AuthAdminAuditLogsRoute,
  AuthAdminProjectsRoute: AuthAdminProjectsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminVendorsRoute: AuthAdminVendorsRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthBrokerRouteChildren {
  AuthBrokerDocumentRequestsRoute: typeof AuthBrokerDocumentRequestsRoute
  AuthBrokerSettingsRoute: typeof AuthBrokerSettingsRoute
  AuthBrokerIndexRoute: typeof AuthBrokerIndexRoute
  AuthBrokerMonthlyReportsIdRoute: typeof AuthBrokerMonthlyReportsIdRoute
  AuthBrokerProjectsIdRoute: typeof AuthBrokerProjectsIdRoute
  AuthBrokerMonthlyReportsIndexRoute: typeof AuthBrokerMonthlyReportsIndexRoute
  AuthBrokerProjectsIndexRoute: typeof AuthBrokerProjectsIndexRoute
}

const AuthBrokerRouteChildren: AuthBrokerRouteChildren = {
  AuthBrokerDocumentRequestsRoute: AuthBrokerDocumentRequestsRoute,
  AuthBrokerSettingsRoute: AuthBrokerSettingsRoute,
  AuthBrokerIndexRoute: AuthBrokerIndexRoute,
  AuthBrokerMonthlyReportsIdRoute: AuthBrokerMonthlyReportsIdRoute,
  AuthBrokerProjectsIdRoute: AuthBrokerProjectsIdRoute,
  AuthBrokerMonthlyReportsIndexRoute: AuthBrokerMonthlyReportsIndexRoute,
  AuthBrokerProjectsIndexRoute: AuthBrokerProjectsIndexRoute,
}

const AuthBrokerRouteWithChildren = AuthBrokerRoute._addFileChildren(
  AuthBrokerRouteChildren,
)

interface AuthBusinessRouteChildren {
  AuthBusinessProyekRoute: typeof AuthBusinessProyekRoute
  AuthBusinessIndexRoute: typeof AuthBusinessIndexRoute
}

const AuthBusinessRouteChildren: AuthBusinessRouteChildren = {
  AuthBusinessProyekRoute: AuthBusinessProyekRoute,
  AuthBusinessIndexRoute: AuthBusinessIndexRoute,
}

const AuthBusinessRouteWithChildren = AuthBusinessRoute._addFileChildren(
  AuthBusinessRouteChildren,
)

interface AuthVendorRouteChildren {
  AuthVendorDealsRoute: typeof AuthVendorDealsRoute
  AuthVendorNotificationsRoute: typeof AuthVendorNotificationsRoute
  AuthVendorOpportunitiesRoute: typeof AuthVendorOpportunitiesRoute
  AuthVendorPerformanceRoute: typeof AuthVendorPerformanceRoute
  AuthVendorPortfolioPerformanceRoute: typeof AuthVendorPortfolioPerformanceRoute
  AuthVendorSettingsRoute: typeof AuthVendorSettingsRoute
  AuthVendorIndexRoute: typeof AuthVendorIndexRoute
  AuthVendorActiveProjectsIdRoute: typeof AuthVendorActiveProjectsIdRoute
  AuthVendorPortfolioIdRoute: typeof AuthVendorPortfolioIdRoute
  AuthVendorProjectsIdRoute: typeof AuthVendorProjectsIdRoute
  AuthVendorTendersIdRoute: typeof AuthVendorTendersIdRoute
  AuthVendorActiveProjectsIndexRoute: typeof AuthVendorActiveProjectsIndexRoute
  AuthVendorPortfolioIndexRoute: typeof AuthVendorPortfolioIndexRoute
  AuthVendorProjectsIndexRoute: typeof AuthVendorProjectsIndexRoute
  AuthVendorTendersIndexRoute: typeof AuthVendorTendersIndexRoute
}

const AuthVendorRouteChildren: AuthVendorRouteChildren = {
  AuthVendorDealsRoute: AuthVendorDealsRoute,
  AuthVendorNotificationsRoute: AuthVendorNotificationsRoute,
  AuthVendorOpportunitiesRoute: AuthVendorOpportunitiesRoute,
  AuthVendorPerformanceRoute: AuthVendorPerformanceRoute,
  AuthVendorPortfolioPerformanceRoute: AuthVendorPortfolioPerformanceRoute,
  AuthVendorSettingsRoute: AuthVendorSettingsRoute,
  AuthVendorIndexRoute: AuthVendorIndexRoute,
  AuthVendorActiveProjectsIdRoute: AuthVendorActiveProjectsIdRoute,
  AuthVendorPortfolioIdRoute: AuthVendorPortfolioIdRoute,
  AuthVendorProjectsIdRoute: AuthVendorProjectsIdRoute,
  AuthVendorTendersIdRoute: AuthVendorTendersIdRoute,
  AuthVendorActiveProjectsIndexRoute: AuthVendorActiveProjectsIndexRoute,
  AuthVendorPortfolioIndexRoute: AuthVendorPortfolioIndexRoute,
  AuthVendorProjectsIndexRoute: AuthVendorProjectsIndexRoute,
  AuthVendorTendersIndexRoute: AuthVendorTendersIndexRoute,
}

const AuthVendorRouteWithChildren = AuthVendorRoute._addFileChildren(
  AuthVendorRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthBrokerRoute: typeof AuthBrokerRouteWithChildren
  AuthBusinessRoute: typeof AuthBusinessRouteWithChildren
  AuthVendorRoute: typeof AuthVendorRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthBrokerRoute: AuthBrokerRouteWithChildren,
  AuthBusinessRoute: AuthBusinessRouteWithChildren,
  AuthVendorRoute: AuthVendorRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BondsRouteChildren {
  BondsIndexRoute: typeof BondsIndexRoute
}

const BondsRouteChildren: BondsRouteChildren = {
  BondsIndexRoute: BondsIndexRoute,
}

const BondsRouteWithChildren = BondsRoute._addFileChildren(BondsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  BondsRoute: BondsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
